### ISSUE TITLE
android:inputType=“textEmailAddress” not Reconized

### ISSUE THREAD

**Issue by CelticParser** [tikivn/AutoCompleteEmail#3]
The `vn.tiki.widgets.AutoCompleteEmailEditText` class does not implement the `android:inputType` [or recognized it in the XML layout file] thus not bring up a soft keyboard that's more suitable for email address entry.

This causes the user an extra step by having to press the shift key to access the `@` key.

In my work-around I have to do the following within the `onCreate()`:
 
```javascript
inputEmail = (AutoCompleteEmailEditText) findViewById(R.id.email);

inputEmail.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);
```

I believe line #110 | #111, `setInputType()` is where your change needs updating.

Can you please Implement this in the `AutoCompleteEmailEditText` class?

thnx

**Comment by dbof10** [comment]
Which soft keyboard do you use? I need to check it out. Try those flags `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS | InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS` if it works. I'll fix it soon.  Thank you.

**Comment by CelticParser** [comment]
Yes, `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS | InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS` works. I'm testing on a US keyboard on a Nexus 6P.

Thnx

**Comment by dbof10** [comment]
#3 fixed
